# Generated by Django 5.0.7 on 2024-07-29 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0002_curso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
